[workspace]
resolver = "2"
members = ["catwalk", "puccinier", "whiskers"]
default-members = ["catwalk"]

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
strip = true

[profile.release.package.catppuccin-catwalk]
opt-level = "s"
